// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VarejistaProduto.Server.Data;

#nullable disable

namespace VarejistaProduto.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230614024915_InputDadosTabelaProdutos")]
    partial class InputDadosTabelaProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VarejistaProduto.Shared.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2023, 6, 13, 23, 49, 14, 998, DateTimeKind.Local).AddTicks(9368),
                            Descricao = "A Banana Nanica vai bem pura mesmo, banana com aveia, banana à milanesa e também pode ser utilizada para o preparo de bolos, tortas, entre outros. Fonte: Conquiste Sua Vida",
                            Nome = "Banana Nanica",
                            PrecoVenda = 6.30m,
                            Quantidade = 20,
                            Tipo = "Orgânico"
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2023, 6, 13, 23, 49, 14, 998, DateTimeKind.Local).AddTicks(9379),
                            Descricao = "A Uva Thompson é uma das queridinhas espécies de uva sem sementes. Sua origem é turca ou grega, mas devido ao clima com muito sol e chuvas esporádicas, seu cultivo se adaptou muito bem ao clima brasileiro.",
                            Nome = "Uva Thompsom",
                            PrecoVenda = 12.30m,
                            Quantidade = 12,
                            Tipo = "Não orgânico"
                        },
                        new
                        {
                            Id = 3,
                            DataCadastro = new DateTime(2023, 6, 13, 23, 49, 14, 998, DateTimeKind.Local).AddTicks(9381),
                            Descricao = "A batata doce é uma fonte de carboidrato saudável, famosa por ser o alimento predileto de quem quer ganhar massa muscular.",
                            Nome = "Batata Doce",
                            PrecoVenda = 5.40m,
                            Quantidade = 13,
                            Tipo = "Orgânico"
                        },
                        new
                        {
                            Id = 4,
                            DataCadastro = new DateTime(2023, 6, 13, 23, 49, 14, 998, DateTimeKind.Local).AddTicks(9383),
                            Descricao = "Os Ovos Vermelhos Caipira Ito Vita são frescos, produzidos por galinhas criadas em espaços adequados aos seus comportamentos naturais como ciscar o chão, bater asas e se empoleirar.",
                            Nome = "Ovos Caipira",
                            PrecoVenda = 23.30m,
                            Quantidade = 6,
                            Tipo = "Orgânico"
                        },
                        new
                        {
                            Id = 5,
                            DataCadastro = new DateTime(2023, 6, 13, 23, 49, 14, 998, DateTimeKind.Local).AddTicks(9384),
                            Descricao = "O tomate italiano tem uma consistência mais encorpada em relação aos outros tipos existentes.",
                            Nome = "Tomate Italiano",
                            PrecoVenda = 10.30m,
                            Quantidade = 30,
                            Tipo = "Não orgânico"
                        },
                        new
                        {
                            Id = 6,
                            DataCadastro = new DateTime(2023, 6, 13, 23, 49, 14, 998, DateTimeKind.Local).AddTicks(9386),
                            Descricao = "A batata é um alimento presente diariamente na mesa dos brasileiros, um alimento de fácil cultivo, existem variedades de batatas, com diferentes tamanhos e cores.",
                            Nome = "Batata",
                            PrecoVenda = 6.34m,
                            Quantidade = 40,
                            Tipo = "Não orgânico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
